#include "RangeTrackPositionReader.h"

/*
 *
 *
 */

/*
long RangeTrackPositionReader::GetPosition()
{
    return 0;
}
*/


/*
long RangeTrackPositionReader::GetYPosition()
{
    return 0;
}

long RangeTrackPositionReader::GetThetaPosition()
{
    return 0;
}
*/

// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000CE9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackPositionReader::GoToPosition(long position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6fa0052a:12469e52649:-8000:0000000000001117 begin
{

}
// section -64--88-1-7--6fa0052a:12469e52649:-8000:0000000000001117 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

