#include "RangeTrackVectorFilter.h"

RangeTrackVectorFilter::RangeTrackVectorFilter(vector<RangeTrackFilter *> filters)
{
    m_filter_list = filters;
    m_temp_filter_results.resize(m_filter_list.size()-1);
}

void RangeTrackVectorFilter::AddFilter(RangeTrackFilter *filter)
{
    m_filter_list.push_back(filter);
    m_temp_filter_results.resize(m_filter_list.size()-1);
}

void RangeTrackVectorFilter::Filter(vector<long> & raw, vector<long> & filtered)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FC6 begin
{
    int filter_index = 0;

    if(m_temp_filter_results.size()) // if there are any temp vectors
    {
        m_filter_list[filter_index]->Filter(raw, m_temp_filter_results[filter_index]); // copy to first vector

        filter_index++;

        if(filter_index < m_temp_filter_results.size())
        {
            for(; filter_index < m_temp_filter_results.size(); filter_index++)
            {
                m_filter_list[filter_index]->Filter(m_temp_filter_results[filter_index-1], m_temp_filter_results[filter_index]); // copy through the vector chain
            }
        }

        m_filter_list[filter_index]->Filter(m_temp_filter_results[filter_index-1], filtered); // copy from the last vector
    }
    else if(m_filter_list.size() == 1)
    {
        m_filter_list[filter_index]->Filter(raw, filtered); // only 1 filter, direct copy
    }
}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FC6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
