#include "RangeTrackRangeReader.h"

/*
 * 
 */



short RangeTrackRangeReader::GetRange()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D11 begin
{
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D11 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

