#include "RangeTrackCreateDistancePositionReader.h"





RangeTrackCreateDistancePositionReader::RangeTrackCreateDistancePositionReader()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016F8 begin
{
    
}
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016F8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

long RangeTrackCreateDistancePositionReader::GetPosition()
{
	return(gc_distance);
}

/*
long RangeTrackCreateDistancePositionReader::GetThetaPosition()
{
	// Convert degrees to milliradians... this isn't very accurate, we should switch to the raw encoders for this function
	return((gc_angle+90) * 3142 / 180); // The +90 is solely for testing; we should use a Sum reader for that
}
*/

// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016FA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackCreateDistancePositionReader::GoToPosition(long position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016FC begin
{
    
}
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016FC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

