#include "RangeTrackSumPositionReader.h"

RangeTrackSumPositionReader::RangeTrackSumPositionReader(vector<RangeTrackPositionReader> readers)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010E5 begin
{

}
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010E5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

RangeTrackPositionReader* RangeTrackSumPositionReader::GetReader(int index)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010DE begin
{
}
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010DE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackSumPositionReader::SetReader(int index, RangeTrackPositionReader* reader)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010E1 begin
{

}
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010E1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

long RangeTrackSumPositionReader::GetPosition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D03 begin
{
    return 0;
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D03 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackSumPositionReader::GoToPosition(long position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6fa0052a:12469e52649:-8000:0000000000001122 begin
{

}
// section -64--88-1-7--6fa0052a:12469e52649:-8000:0000000000001122 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

