#include "RangeTrackSingleServoPositionReader.h"

RangeTrackSingleServoPositionReader::RangeTrackSingleServoPositionReader(int port)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000F9E begin
{

}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000F9E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int RangeTrackSingleServoPositionReader::GetPort()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FAA begin
{
    return 0;
}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FAA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackSingleServoPositionReader::SetPort(int port)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FA1 begin
{

}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FA1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

long RangeTrackSingleServoPositionReader::GetPosition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D01 begin
{
    return 0;
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D01 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackSingleServoPositionReader::GoToPosition(long position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6fa0052a:12469e52649:-8000:000000000000111F begin
{

}
// section -64--88-1-7--6fa0052a:12469e52649:-8000:000000000000111F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

