#include "RangeTrackDiffPositionReader.h"

RangeTrackDiffPositionReader::RangeTrackDiffPositionReader(vector<RangeTrackPositionReader*> readers)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010FC begin
{
    m_position_readers = readers;
}
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010FC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

RangeTrackPositionReader* RangeTrackDiffPositionReader::GetReader(int index)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010F0 begin
{
    printf("Error: GetReader\n");
}
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010F0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackDiffPositionReader::SetReader(int index, RangeTrackPositionReader* reader)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010F4 begin
{
    printf("Error: SetReader\n");
}
// section -64--88-1-7--6b4a04c1:1246524e722:-8000:00000000000010F4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

long RangeTrackDiffPositionReader::GetPosition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D05 begin
{
    return m_position_readers[0]->GetPosition() - m_position_readers[1]->GetPosition();
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D05 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackDiffPositionReader::GoToPosition(long position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6fa0052a:12469e52649:-8000:0000000000001125 begin
{

}
// section -64--88-1-7--6fa0052a:12469e52649:-8000:0000000000001125 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

