#include "RangeTrackFilter.h"


RangeTrackFilter::RangeTrackFilter()
{
}

void RangeTrackFilter::Filter(vector<long> & raw, vector<long> & filtered)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FC2 begin
{
	while(filtered.size() < raw.size())
	{
		filtered.push_back(raw[filtered.size()]);
	}
}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FC2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

