#include "RangeTrackSonarRangeReader.h"

RangeTrackSonarRangeReader::RangeTrackSonarRangeReader(int port)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FB3 begin
{

}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FB3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int RangeTrackSonarRangeReader::GetPort()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FAE begin
{
    return 0;
}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FAE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackSonarRangeReader::SetPort(int port)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FA7 begin
{

}
// section -64--88-1-7-672b1494:1245fa68a9a:-8000:0000000000000FA7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

short RangeTrackSonarRangeReader::GetRange()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D15 begin
{
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D15 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

