#include "RangeTrackTimePositionReader.h"





RangeTrackTimePositionReader::RangeTrackTimePositionReader()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016F8 begin
{

}
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016F8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

/*
long RangeTrackTimePositionReader::GetXPosition()
{
	return(gc_distance);
}
*/

long RangeTrackTimePositionReader::GetPosition()
{
	return( (long)(1000.0 * seconds()) );
}

// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016FA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackTimePositionReader::GoToPosition(long position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016FC begin
{

}
// section -64--88-1-8-45c899e5:124a28211a8:-8000:00000000000016FC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


