#include "RangeTrackSingleMotorPositionReader.h"

RangeTrackSingleMotorPositionReader::RangeTrackSingleMotorPositionReader(int port)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D27 begin
{
    m_port = port;
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D27 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int RangeTrackSingleMotorPositionReader::GetPort()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D2E begin
{
    return m_port;
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D2E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackSingleMotorPositionReader::SetPort(int port)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D30 begin
{
    m_port = port;
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000D30 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

long RangeTrackSingleMotorPositionReader::GetPosition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000CFF begin
{
    return get_motor_position_counter(m_port);
}
// section -64--88-1-7--2e422ddc:1245f06c020:-8000:0000000000000CFF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void RangeTrackSingleMotorPositionReader::GoToPosition(long position)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-7--6fa0052a:12469e52649:-8000:000000000000111C begin
{

}
// section -64--88-1-7--6fa0052a:12469e52649:-8000:000000000000111C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

